---
- name: "Get related types to a Job Template and write to file"
  ansible.builtin.uri:
    url: "{{ awx_api }}/organizations/{{ org_id }}/job_templates/"
    method: GET
    headers:
      Authorization: "Bearer {{ ansible_controller_token }}"
    validate_certs: false
    return_content: true
    body_format: json
    status_code: 200
  register: job_templates

- name: "DEBUG job templates"
  ansible.builtin.debug:
    var: job_templates

- name: "Fail if job template not found"
  ansible.builtin.fail:
    msg: "Job template not found"
  when: job_templates.json.count == 0

- name: "Set Job Template ID"
  ansible.builtin.set_fact:
    job_template_id: "{{ job_templates.json.results[0].id }}"

- name: "Find job templates related types"
  ansible.builtin.set_fact:
    job_templates_related_items: "{{ job_templates.json.results[0].related | dict2items | selectattr('key', 'in', ['labels', 'inventory', 'project', 'organization', 'credentials', 'schedules', 'notification_templates_started', 'notification_templates_success', 'notification_templates_error', 'survey_spec'] ) }}"

- name: "DEBUG job template related items"
  ansible.builtin.debug:
    var: job_templates_related_items

- name: "Loop through related items and get each"
  ansible.builtin.uri:
    url: "{{ awx_url }}/{{ item.value }}"
    method: GET
    headers:
      Authorization: "Bearer {{ ansible_controller_token }}"
    return_content: true
    body_format: json
    status_code: 200
    validate_certs: false
  loop: "{{ job_templates_related_items }}"
  loop_control:
    label: "{{ item.key }}"
  register: job_templates_related_items
  no_log: true

- name: "Show results of related items"
  ansible.builtin.debug:
    msg: |
      Related item '{{ item.item.key }}' data:
      {{ item.json }}
  loop: "{{ job_templates_related_items.results }}"

- name: "Write related types to local file"
  ansible.builtin.copy:
    content: "{{ item.json | to_nice_json }}"
    dest: "{{ json_upload_dir }}/{{ item.item.key }}.json"
    mode: '0644'
  loop: "{{ job_templates_related_items.results }}"
  loop_control:
    label: "{{ item }}"

- name: "Begin file upload procedure"
  ansible.builtin.include_tasks: upload_files.yml

