---
- name: "Export orgnization resources" 
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: 
    - vars/common.yml
  vars:
    resources:
      - job_templates
      - schedules
  tasks:
    - name: "Get Organization {{ org_id }} resources"
      ansible.builtin.include_tasks: organizations.yml
      when: 
        - _organizations is defined
        - _organizations is true

    - name: "Get Organization {{ org_id }} job templates"
      ansible.builtin.include_tasks: job_templates.yml
      when: 
        - _job_templates is defined
        - _job_templates is true

    - name: "End Play"
      ansible.builtin.meta: end_play

