---
- name: "Demo Paybook"
  hosts: all
  gather_facts: false
  tasks:
  - name: "Hello world"
    ansible.builtin.debug:
      msg: "Hello Word!"
      
  - name: Get the current date.
    command: date
    register: current_date
    changed_when: false

  - name: Print the current date.
    debug:
      msg: "{{ current_date.stdout }}"
